### ISSUE TITLE
Conflicting packages `optimum-haystack`  and `instructor-embedders-haystack`

### ISSUE THREAD

**Issue by ArzelaAscoIi** [deepset-ai/haystack-core-integrations#929]
**Describe the bug**
- for optimum-haystack the we request [sentence-transformers>=2.3](https://github.com/deepset-ai/haystack-core-integrations/blob/b8e2623014be9ab7410d98832e25eda46923b04c/integrations/optimum/pyproject.toml#L36)
- for nstructor-embedders-haystack we  [exclude 2.3 or greater](https://github.com/deepset-ai/haystack-core-integrations/blob/b8e2623014be9ab7410d98832e25eda46923b04c/integrations/instructor_embedders/pyproject.toml#L39) 

These packages are incompatible

**To Reproduce**
- just install both packages 

**Describe your environment (please complete the following information):**
 - Haystack version:
 - Integration version:

**Comment by julian-risch** [comment]
@ArzelaAscoIi After a first look at the dependencies my guess is that we can remove the <2.3.0 pin from the instructor-embedder integration because there is also no upper limit for the version set here https://github.com/xlang-ai/instructor-embedding/blob/main/requirements.txt#L9

**Comment by anakin87** [comment]
I'm not sure... I pinned the dependency because Instructor Embeddings were not working with `sentence_transformers>=2.3.0`. https://github.com/deepset-ai/haystack-core-integrations/pull/289

Then they updated the main branch (https://github.com/xlang-ai/instructor-embedding/pull/112), but a new package was not released. https://pypi.org/project/InstructorEmbedding/#history; https://github.com/xlang-ai/instructor-embedding/pull/112#issuecomment-2052409621.

So, we should try...

**Comment by anakin87** [comment]
I tried to unpin the dependency and using `sentence-transformers==3.0.1` (latest),
I get these errors when running the tests:

> FAILED tests/test_instructor_document_embedder.py::TestInstructorDocumentEmbedder::test_run - TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'
FAILED tests/test_instructor_text_embedder.py::TestInstructorTextEmbedder::test_run - TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'

**Comment by julian-risch** [comment]
Thanks @anakin87 ! That means at the moment the two packages are not compatible and there is nothing we can do about it, which is why I suggest we close this issue.
