### ISSUE TITLE
Langfuse trace failing apps for flushing

### ISSUE THREAD

**Issue by touhi99** [deepset-ai/haystack-core-integrations#1138]
**Describe the bug**
Following the documentation here [Langfuse](https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/langfuse/src/haystack_integrations/components/connectors/langfuse/langfuse_connector.py ), I am adding trace flush on the fastapi

```
@asynccontextmanager
async def lifespan(app: FastAPI):
    tracer.actual_tracer.flush()
```

I am getting the following error: 

```
  File "C:\Users\touhidul.alam\Anaconda3\envs\shs\Lib\site-packages\starlette\routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\touhidul.alam\Anaconda3\envs\shs\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\touhidul.alam\Desktop\shs\shs-rag-backend\src\rag\api\api.py", line 17, in lifespan
    tracer.actual_tracer.flush()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NullTracer' object has no attribute 'flush'

ERROR:    Application startup failed. Exiting.
```

**Describe your environment (please complete the following information):**
 - OS:Windows
 - Haystack version: 2.6.0
 - Integration version: 0.5.0

it was working with langfuse-haystack==0.2.0 but after upgrading to haystack 0.5.0, it's not working anymore. Any solution idea? Thanks
